site_name: Git Commands Notes
site_description: Documentation for Git commands and branching strategies
site_author: Dyson Liu
repo_url: https://microsystex.github.io/git-commands-notes/

theme:
  name: material

nav:
  - Git Branch Planning: git-branch-planning.md
  - Related Commands Summary: related-commands-summary.md
